version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  extra_user_setup:
    image: mysql:latest
    command: >
      bash -c "
      mysql -hmysql -uroot -pmy-secret-pw -e '
        CREATE DATABASE IF NOT EXISTS info_esp32;
        CREATE USER IF NOT EXISTS '\''test'\''@'\''%'\'' IDENTIFIED BY '\''abcd1234'\''; 
        GRANT ALL PRIVILEGES ON info_esp32.* TO '\''test'\''@'\''%'\'';
      '
      "
    depends_on:
      - mysql

volumes:
  mysql-data:
